// Import the 'express' module (for more informations: https://www.npmjs.com/package/express)...
var express = require('express');

// Import the 'serve-favicon' module (for more informations: https://www.npmjs.com/package/serve-favicon)...
var favicon = require('serve-favicon');

// Import the 'negotiator' module (for more informations: https://www.npmjs.com/package/negotiator)...
var Negotiator = require('negotiator');

// Import the 'olsonTZNPMmodule' module (for more informations: https://github.com/Vicken-Ghoubiguian/olsonTZNPMmodule)...
var olsonTZNPMmodule = require('@wicken/olsonTZNPMmodule');

// Import the 'openWeather' module (for more informations: https://github.com/Vicken-Ghoubiguian/openWeather)...
var openWeather = require('@wicken/openweather');