// Import the 'express' module (for more informations: )...
var express = require('express');

// Import the 'serve-favicon' module (for more informations: )...
var favicon = require('serve-favicon');

// Import the 'negotiator' module (for more informations: )...
var Negotiator = require('negotiator');

// Import the 'olsonTZNPMmodule' module (for more informations: )...
var olsonTZNPMmodule = require('@wicken/olsonTZNPMmodule');

// Import the 'openWeather' module (for more informations: )...
var openWeather = require('@wicken/openweather');